function menuStyles() {
    test("TITLETITLE", async (t) => {
        await t
            .typeText("#urlOrPDB", "1xdn")
            .click("#submit")
            .expect(Selector("#status").innerText)
            .eql("Mol Loaded", "Molecule loaded!", {timeout: 15000})
            // .click("#modal-close-button-load-save-modal")
            .click("#menu-button")
            .click("#btn-Styles")
            .click("#btn-Styles-Components")
            .click("#btn-Styles-Components-LigandAll")
            .click("#btn-Styles-Components-LigandAll-Surface")
            .click("#btn-Styles-Components-LigandAll-Surface-Colors")
            .click("#btn-Styles-Components-LigandAll-Surface-Colors-White")
            .wait(3000)
            .click("#btn-Styles-Components-LigandContextAll")
            .click("#btn-Styles-Components-LigandContextAll-Sphere")
            .click("#btn-Styles-Components-LigandContextAll-Sphere-ColorSchemes")
            .click("#btn-Styles-Components-LigandContextAll-Sphere-ColorSchemes-Element")
            .wait(3000)
            .click("#btn-Styles-Components-Protein")
            .click("#btn-Styles-Components-Protein-All")
            .click("#btn-Styles-Components-Protein-All-Cartoon")
            .click("#btn-Styles-Components-Protein-All-Cartoon-ColorSchemes")
            .click("#btn-Styles-Components-Protein-All-Cartoon-ColorSchemes-AminoAcid")
            .wait(3000)
            .click("#btn-Styles-Selections")
            .click("#btn-Styles-Selections-ResidueIndex")
            .click("#btn-Styles-Selections-ResidueIndex-307541")
            .click("#btn-Styles-Selections-ResidueIndex-307541-503506")
            .click("#btn-Styles-Selections-ResidueIndex-307541-503506-505")
            .click("#btn-Styles-Selections-ResidueIndex-307541-503506-505-Sphere")
            .click("#btn-Styles-Selections-ResidueIndex-307541-503506-505-Sphere-Colors")
            .click("#btn-Styles-Selections-ResidueIndex-307541-503506-505-Sphere-Colors-Orange")
            .wait(1000)
            .click("#btn-Styles-RemoveExisting")
            .click("#btn-Styles-RemoveExisting-AllLigandSurfaceWhite")
            .wait(1000)
            .click("#modal-close-button-menu-2d")
    });
}

menuStyles();
